#!/usr/bin/env bash
# shellbot.sh - irc bot
# author: baccenfutter, c-base.org
# original code from: sean b. palmer, inamidst.com

nick=tank
server=${1:-localhost}
prefixchar="$"


# load config
. etc/*.conf

function answer
{
	msg="$@"
	line=""
	
	# first, fetch errors
	if [[ "$msg" == "" ]]; then
		echo "error: can't send privmsg - missing parameter!"
		return 0
	fi
	line="privmsg"
	
	# check for query or channel
	if [[ "${chan:0:1}" == "#" ]]; then
		line="$(echo $line $chan :)"
		# check for $config_reply_nick
		if [[ $config_reply_nick == true ]]; then line="$(echo $line $source_nick:)"; fi
	else
		line=$(echo $line $source_nick :)
	fi

	# finally, add $msg and burst it out
	line="$(echo $line$msg)"
	echo "$line" >> $nick.input
}

function acl_auth
{
	username=$1
	password=$2

	acl=$(cat etc/users | grep "$username:$password" | cut -d: -f3)
	
	if [[ -n $acl ]]; then
		echo "$hostmask:$username:$acl" >> $nick.acl
		return
	fi
}

function acl_check
{
	case $1 in
		owner)
		acl=$1
		;;
		admin)
		acl={owner,admin}
		;;
		user)
		acl={owner,admin,user}
		;;
	esac

	echo "»»»ACL_CHECK: $(cat $nick.acl | grep $hostmask | cut -d: -f3)"

	if [[ $(cat $nick.acl | grep $hostmask | cut -d: -f3) == $acl ]]; then
		return 0
	else
		return 1
	fi
}



### the bot's main body ###

. src/connect
. src/auth

tail -f $nick.input | telnet $server 6667 | \
while true
	do read line || break

	echo $(date +%h:%m:%s) $line
	
	if [[ "${line:0:1}" == ":" ]]; then
		. src/main
	else
		if [[ "${line:0:4}" == "PING" ]]; then
			. src/global_ping
		fi
	fi
done

