#!/usr/bin/env bash
# shellbot.sh - irc bot
# author: baccenfutter, c-base.org
# original code from: sean b. palmer, inamidst.com

# source config
. etc/*

function answer
{
	msg="$@"
	line=""
	
	# first, fetch errors
	if [[ "$msg" == "" ]]; then
		echo "error: can't send privmsg - missing parameter!"
		return 0
	fi
	line="PRIVMSG"
	
	# check for query or channel
	if [[ "${chan:0:1}" == "#" ]]; then
		line="$(echo $line $chan :)"
		# check for $config_reply_nick
		if [[ $config_reply_nick == true ]]; then line="$(echo $line $source_nick:)"; fi
	else
		line=$(echo $line $source_nick :)
	fi

	# finally, add $msg and burst it out
	line="$(echo $line$msg)"
	echo "$line" >> $nick.input
}

function acl_auth
{
	username=$1
	password=$2
	acl=$(egrep ^$username:$password < var/users | cut -d: -f3)
	if [[ -n $acl ]]; then
		echo "$hostmask:$username:$acl" >> $nick.acl
		return 0
	else
		return 1
	fi
}

function acl_check
{
	case $1 in
		owner)required_acl=1;;
		admin)required_acl=2;;
		user)required_acl=3;;
	esac

	acl="$(cat $nick.acl | grep $hostmask | cut -d: -f3)"
	case $acl in
		owner)acl=1;;
		admin)acl=2;;
		user)acl=3;;
		*)acl=9999;;
	esac

	if [[ $acl -le $required_acl ]] ; then
		return 0
	else
		return 1
	fi
}



### the bot's main body ###

. bin/connect

tail -f $nick.input | telnet $server $port | \
while true
	do read line || break

	echo $(date +%h:%m:%s) $line
	
	if [[ "${line:0:1}" == ":" ]]; then
		. bin/main
	else
		if [[ "${line:0:4}" == "PING" ]]; then
			. bin/global_ping
		fi
	fi
done

