#!/bin/bash
# Script: answer
# Description: This script formulates an IRC PRIVMS with all received
#              arguments as the message body and >>'s it into the $input_file.

msg="$@"
output=''

# first, fetch errors
if [[ "$msg" == "" ]]; then
	echo "error: can't send privmsg - missing parameter!"
	return 0
fi
# start assembling the response output
output="PRIVMSG"

# check for query or channelnel
if $query; then
	output=$(echo $output $nickname)
else
	output="$(echo $output $channel)"
	# check for $config_reply_nick
	if [[ $config_reply_nick == true ]]; then
		output="$(echo $output $nickname)"
	fi
fi

# finally, add $msg and burst it out
output="$(echo $output :$msg)"
echo "$output" >> $input_file

