#!/bin/bash
# Script: connect
# Description: Script for hand-shaking with the IRC server
#
# - Creates/Resets ACL management file -> $aclfile
# - Creates/Resets input file -> $inputfile
# - Sets $owner variable
# - Sets IRC username, realname and nickname
# - Initiates sub-script to join all configured channels

rm -rf $run_dir
mkdir -p $channel_dir

owner=$(egrep " owner$" < $user_file | cut -d' ' -f1)
echo Setting owner to: $owner

echo Connecting...
echo "nick $nick" > $input_file
echo "user $nick +iw $nick :$owner" >> $input_file

{ sleep 3
echo -n "Auto-joining channels: "
for channel in $(cat $channel_file)
do
	[[ -n $channel ]] && echo "join " $channel >> $input_file && echo -n $channel
done
echo; } &
