#!/bin/bash
# Script: incoming
# Description: this script parses the incoming IRC stream

# remove prepending colon
incoming=${incoming:1}

# cut out the three first fields
hostmask=$(echo $incoming | cut -d' ' -f1)
msgtype=$(echo $incoming | cut -d' ' -f2)
channel=$(echo $incoming | cut -d' ' -f3)
nickname=$(echo $hostmask | cut -d'!' -f1)
origin=$(echo $hostmask | cut -d'!' -f2)
username=$(echo $origin | cut -d '@' -f1)
hostname=$(echo $origin | cut -d'@' -f2)

# tail $incoing
incoming=${incoming:$(expr ${#hostmask} + ${#msgtype} + ${#channel} + 3 )}

# check if we have a query or a channel message
[[ $channel == $nick ]] && query=true || query=false

# for design reasons, server messages and chat events have seperate directories
if [[ $hostmask == $origin ]]; then
	[[ -f $trigger_dir/server/$msgtype ]] && . $trigger_dir/server/$msgtype
else
	[[ -f $trigger_dir/message/$msgtype ]] && . $trigger_dir/message/$msgtype
fi

