#!/bin/bash
# Script: 311
# Description: Script for parsing the whois response line containing the
#              hostmask data.

# this script is temporarily disabled
#return 0

# cut the incoming nickname, username and hostmask
incoming_nickname="$(echo $incoming | cut -d' ' -f1)"
incoming_username="$(echo $incoming | cut -d' ' -f2)"
incoming_hostmask="$(echo $incoming | cut -d' ' -f3)"

echo Incoming: server trigger 311 "[WHOIS RESPONSE]" for $incoming_nickname
sed -i "s/$incoming_nickname/$incoming_nickname $incoming_username $incoming_hostmask/g" $channel_dir/*

