#!/bin/bash
# Script: 353
# Description: parses all nicknames when joining a channel

channel=$(echo $incoming | cut -d' ' -f2)
incoming=$(echo $incoming | cut -d: -f2-)

echo $channel: $incoming

for nickname in $(echo $incoming)
do
	echo $nickname >> $channel_dir/$channel
	# [[ $(echo $nickname | egrep "^(\@|\+)") ]] && nickname=${nickname:1}
done

