#!/bin/bash
# Main configuration file

nick='bashdude'
server='localhost'
port='6667'
prefixchar='·'
controlchannel='#bashdude'

# answers
part_message='So long and thanks for all the fish!'
quit_message='Silence! I kill you!'
command_not_found='Dont know what you are talking about, dude...'
missing_arguments='Missing arguments!'

# Configuration variables go here:

config_reply_nick=false
config_allow_user_reg=false


