#!/bin/bash
# File: header
# Description: This file sets all $*_dir and $*_file variables. Having a file
#              like this centralizes global variable setting, thus providing
#              a bigger overall overview on all the global file and directory
#              vars.

# directories
root_dir=/root/bashdude
bin_dir=$root_dir/bin
etc_dir=$root_dir/etc
usr_dir=$root_dir/usr
	share_dir=$usr_dir/share
		core_dir=$share_dir/core
			mod_dir=$core_dir/modules
			trigger_dir=$core_dore/triggers
var_dir=$root_dir/var
	log_dir=$var_dir/log
	run_dir=$var_dir/run
		channel_dir=$run_dir/channels


# files
input_file=$run_dir/$nick.input
user_file=$etc_dir/users
acl_file=$run_dir/$nick.acl

# finally, source the main configuration file
. $etc/config
