#!/bin/bash
# Script: chanlogger
# Description: Basic channel logging script
#
# - Creates $directory log/%Y/%m/%d/$server
# - Timestamped logging takes place in $directory/$chan

directory=log/$(date +%Y)/$(date +%m)/$(date +%d)/$server/ &> /dev/null
mkdir -p $directory &> /dev/null
echo $(date +%R:%S) - $source_nick: $msg >> $directory/$chan
