#!/bin/bash
# Script: chan
# Description: CLI to the bot's channel manager
#
# - Takes sub-commands:
#   - list			-	Lists all channels the bot is in
#   - list voice
#   - list op

subcmd="$1"
arg="$2"

case $subcmd in
	list)
		if [[ -z $arg ]]; then
			answer "Here comes my channel list, dude:"
			for channel in $(ls var/run/$server/)
			do answer $channel; done
		elif [[ $arg == 'voice' ]]; then
			answer "Channels that listen to me:" $(basename $(grep -rl "^+$nick$" var/run/$server))
		elif [[ $arg == 'op' ]]; then
			answer "Channels I own:" $(basename $(grep -rl "^@$nick$" var/run/$server))
		else
			echo 
		fi
		;;
esac
