#!/bin/bash
# Script: deop
# Description: Script for handing -o to users
#
# Required ACL: admin
#
# - Takes $nick_to_deop as argument.

nick_to_deop=${1:-$source_nick}

acl_check admin && mode_check "op" $chan && echo MODE $chan -o $nick_to_deop >> $inputfile || answer "Check permissions, dude!"
