#!/bin/bash
# Script: identify
# Description: Login interface for known users
#
# - Authentication in a channel is prohibited
# - Authenticates user
# - Associates $hostmask with $user and $acl

username="$1"
password="$2"

case $chan in
	# first of all, check if we are authenticating in public
	\#*)
	answer "Don't identify in a channel, dumb-ass!"
	if [[ -n "$password" ]]; then
		answer "Great! Stating your password here was a very smart idea... idot!"
		answer "I am disabling your account, fool."
		egrep ^$username: < var/users > var/users.tmp; mv var/users.tmp var/users
	fi
	;;
	
	# authenticate
	*)
	if egrep ^$hostmask < $nick.acl &> /dev/null; then
		answer "Authentication failed! You are allready logged in."
	else
		if acl_auth $username $password; then
			answer "Authentication successfull!"
		else
			answer "Authentication failed!"
		fi
	fi
esac

