#!/bin/bash

channel=$1
key=$2

if [[ ! ${channel:0:1} == "#" ]]; then channel=\#$channel; fi
if acl_check admin; then
	if cat var/channels | grep $channel &> /dev/null ; then
		answer "How many times do you want me to join that channel, dude?"
	else
		echo $channel $key >> var/channels
		echo JOIN $channel $key >> $nick.input
	fi
else
	answer 'join my ass!'
fi
