#!/bin/bash
# Script: logout
# Description: CLI interface for logging out.
#
# - Unassociates $hostmask with $user and $acl and thus logs the user out

if egrep ^$hostmask < $aclfile > $aclfile.tmp; then
	if [[ $(cat $aclfile | wc -l) == 1 ]]; then echo > $aclfile && rm $aclfile.tmp; else mv $aclfile.tmp $aclfile; fi
	answer "Your are no longer logged in, dude."
else
	answer "I don't know you, dude"
fi
