#!/bin/bash
# Script: op
# Description: Script for handing +o to users
#
# Required ACL: admin
#
# - Takes $nick_to_op as argument.

nick_to_op=${1:-$source_nick}

acl_check admin && mode_check "op" $chan && echo MODE $chan +o $nick_to_op >> $inputfile || answer "Check permissions, dude!"
