#!/bin/bash
# Script: part
# Description: Script for parting from a channel
#
# Required ACL: admin
# 
# - Can be passed directly from #channel without arguments
# - Can be passed as query with #channel as argument
# - The '#' will be prepended automatically if forgotten

channel=${1:-$chan}
if [[ ! ${channel:0:1} == "#" ]]; then channel=\#$channel; fi
if acl_check admin; then
	[[ -f var/run/$server/$chan ]] && echo "PART :$channel" >> $inputfile || answer "That's the first thing I'll do, as soon as I've joined $channel"
else
	answer '$part my ass!'
fi
