#!/bin/bash
# Script: rehash
# Description: Script for rehashing main.conf
#
# - Rehash etc/main.conf and log in stdout

if acl_check owner; then
	echo "Rehashing configuration..."
	. etc/*.conf
	echo "done!"
	answer "Successfully rehashed configuration!"
else
	answer "I don't think so..."
fi
