#!/bin/bash
# Script: seen
# Description: When was $nickname last seen

nickname=$@

[[ -z $nickname ]] && answer "Specify a nickname, dude!" && return

grep -r "$nickname" log/ | tac | head -n1 |  while true
do read line || break
	if [[ $(echo $line | cut -d' ' -f3) == $nickname ]]; then
		answer "I've last seen $nickname \
			on $(echo $line | cut -d' ' -f1 | cut -d: -f2) \
			at $(echo $line | cut -d' ' -f2) \
			in $(basename $(echo $line |cut -d: -f1)) \
			saying $(echo $line | cut -d' ' -f4-)"
	fi
done




