#!/bin/bash

NICKCHAR="!"

# cut the irc line into segments for easier naming in modules and further on
HEADER=$(echo $LINE | cut -d ":" -f 2)
BODY=${LINE:$(expr ${#HEADER} + 1)}
HOSTMASK=$(echo $HEADER | cut -d " " -f 1)
SOURCE_NICK=$(echo $HOSTMASK | cut -d "!" -f 1)
	#echo "HEADER: $HEADER"
	#echo "BODY: $BODY"
	#echo "HOSTMASK: $HOSTMASK"
	#echo "SOURCE_NICK: $SOURCE_NICK"

if [[ "$HOSTMASK" =~ "${NICKCHAR}" ]]; then
	# there is a source_nick
	FLAG=$(echo $HEADER | cut -d " " -f 2)
	if [[ "$FLAG" == "JOIN" ]]; then
		# yet to come...
		continue
	elif [[ "$FLAG" == "PRIVMSG" ]]; then
		# we have a privmsg
		CHAN=$(echo $HEADER | cut -d " " -f 3)
		MSG=${BODY:1}

		if [[ "${MSG:0:1}" == "$PREFIXCHAR" ]]; then
			# we have a command
			MSG=${MSG:1}
		elif echo $MSG | egrep "^$NICK" &> /dev/null ; then
			# we have a command, as well
			MSG=${MSG:$(expr ${#NICK} + 2)}
		elif [[ "$CHAN" == "$NICK" ]]; then
			echo >> /dev/null
		else
			# we do not have a command
			continue
		fi

		# again, split into segments
		COMMAND=$(echo $MSG | cut -d " " -f 1)
		PARAMS=${MSG:$(expr ${#COMMAND} + 1)}

		# run command module
		if [[ -f mods/$COMMAND ]]; then
			. mods/$COMMAND $PARAMS
		else
			answer "Whatever dude..."
		fi
	fi
fi
