#!/bin/bash
# Script: PRIVMS
# Description: script for handling PRIVMSGs

# cut the preceding colon from $incoming
incoming="${incoming:1}"

if [[ ${incoming:0:1} == $prefixchar ]]; then
	# command incoming
	# first assign $command
	command="$(echo $incoming | cut -d' ' -f1)" && command=${command:1}
	# then, tail incoming
	incoming="${incoming:$(expr ${#command} + 2)}"
	# finally, assign $args
	args="$incoming"
	
	# now we source the corresponding core module
	[[ -f $mod_dir/$command ]] && . $mod_dir/$command $args
	[[ -f $extra_mod_dir/$command ]] && . $extra_mod_dir/$command $args
fi
